.TH PshellControl 3 "Sep 2012" "PSHELL" "External Client Control Of Remote Pshell" 
.SH NAME
PshellControl - External Client Program Control of Remote PSHELL Server
.SH DESCRIPTION
This API provides the ability for an external client program to invoke functions
that are registered in a remote program running a pshell server.  This API will
only work on remote programs that are running either a UDP or UNIX pshell server.
.SH SYNOPSIS

#include <PshellControl.h>

/* on success, function returns valid Server ID (sid) to be used as input to other functions */

int pshell_connectServer(const char *controlName_,
                         const char *remoteServer_,
                         unsigned port_ = PSHELL_UNIX_SERVER,
                         unsigned defaultTimeout_ = PSHELL_ONE_MSEC*100);
                         
/* release resources for this connection */

void pshell_disconnectServer(int sid_);

/* issue remote command, function returns status of command */

int pshell_sendCommand1(int sid_, const char *command_, ...);
.br
int pshell_sendCommand2(int sid_, unsigned timeoutOverride_, const char *command_, ...);

/*
.br
 * issue remote command and extract results, function returns number
.br
 * of bytes extracted, must use non-0 wait time to extract results,
.br
 * extracted results is NULL terminated ascii formatted character data
.br
 */

int pshell_sendCommand3(int sid_, char *results_, int size_, const char *command_, ...);
.br
int pshell_sendCommand4(int sid_, char *results_, int size_, unsigned timeoutOverride_, const char *command_, ...);

The above synposis is just a summary of the most relevant part of the API,
to see the full API refer to the include file 'PshellControl.h'

Link with the library libpshell-control

Note, there is also a python implementation of this functionality in the module 'PshellCotrol.py'.  
Its API and examples can be found in the python subdirectory of this install package.
.SH EXAMPLES
See the file pshellControlDemo.cc in the pshell distribution package for a complete 
list of examples of invoking functions in a remote pshell via a local client program.
.SH MT-LEVEL
Safe
.SH SEE ALSO
pshell(1), PshellServer(3)
.SH AUTHOR
Ron Iovine  --  github.com/RonIovine/pshell
