#!/bin/bash

################################################################################
# 
# Copyright (c) 2009, Ron Iovine, All rights reserved.  
#  
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Ron Iovine nor the names of its contributors 
#       may be used to endorse or promote products derived from this software 
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY Ron Iovine ''AS IS'' AND ANY EXPRESS OR 
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
# IN NO EVENT SHALL Ron Iovine BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR 
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE. 
#
#################################################################################

if [ $# -ne 1 ] 
then
  echo "Usage: setPshellLib -stub | -full"
  exit 1
fi
if [ "$1" == "-stub" ] 
then
  if [ -n "$PSHELL_INSTALL" ]
  then
    if [ -e "${PSHELL_INSTALL}/lib/libpshell-server.so" ]
    then
      rm ${PSHELL_INSTALL}/lib/libpshell-server.so
    fi
    ln -s ${PSHELL_INSTALL}/lib/libpshell-server-stub.so ${PSHELL_INSTALL}/lib/libpshell-server.so 
  else
    echo "ERROR: Environment variable PSHELL_INSTALL not defined"
  fi
elif [ "$1" == "-full" ] 
then
  if [ -n "$PSHELL_INSTALL" ]
  then
    if [ -e "${PSHELL_INSTALL}/lib/libpshell-server.so" ]
    then
      rm ${PSHELL_INSTALL}/lib/libpshell-server.so
    fi
    ln -s ${PSHELL_INSTALL}/lib/libpshell-server-full.so ${PSHELL_INSTALL}/lib/libpshell-server.so 
  else
    echo "ERROR: Environment variable PSHELL_INSTALL not defined"
  fi
else
  echo "Usage: setPshellLib -stub | -full"
fi

