.TH pshell 1 "Sep 2012" "PSHELL" "PSHELL - Process Specific Embedded Command Line Shell" 
.SH NAME
pshell/pshell.exp - PSHELL UDP/UNIX client program/Telnet TCP client 'expect' script wrapper
.SH DESCRIPTION
The PSHELL API framework provides the ability to embed a shell type Command Line Interface
(CLI) into any C/C++ application that can then be accessed via either the provided UDP/UNIX
client program (called 'pshell') or via a standard 'telnet' based client.

The 'pshell' program provides the client side command line interface (CLI) functionality
to remotely invoke the callback functions that are registered within a program running a
UDP or UNIX based PshellServer.

The corresponding 'pshell.exp' 'expect' script provides a wrapper around a standard 'telnet'
client to give a similar functionality (i.e. batch mode, command line mode etc) for programs
that are running a TCP based PshellServer as the 'pshell' UDP/UNIX client program .  Use of 
the 'pshell.exp' script is optional, the 'telnet' client can be used directly to interface
to a TCP PshellServer, however, only interactive mode is supported.
.SH USAGE
Usage: pshell -s | [-t<timeout>] {{<hostNameOrIpAddr> <port>} | <unixServerName>}
              [{<command> [<rate> [clear]]} | {-f <fileName> [<rate> [clear]}]

  where:

    -s               - show named servers in $PSHELL_CONFIG_DIR/pshell-client.conf file
    -f               - run commands from a batch file
    -t               - change the default server response timeout
    hostNameOrIpAddr - hostname or IP address of UDP server
    port             - port number of UDP server
    unixServerName   - name of UNIX server
    timeout          - response wait timeout in sec (default=5)
    command          - optional command to execute
    fileName         - optional batch file to execute
    rate             - optional rate to repeat command or batch file (in seconds)
    clear            - clear screen between commands or batch file passes

    NOTE: If no <command> is given, pshell will be started
          up in interactive mode, commands issued in command
          line mode that require arguments must be enclosed 
          in double quotes, commands issued in interactive
          mode that require arguments do not require double
          quotes.

          To get help on a command in command line mode, type
          "<command> ?" or "<command> -h".  To get help in
          interactive mode type 'help' or '?' at the prompt to
          see all available commands, to get help on a single
          command, type '<command> {? | -h}'.  Use TAB completion
          to fill out partial commands and up-arrow to recall
          for command history.
.SH EXAMPLES
See the 'README' file that is distributed with this package for detailed instructions
on using this framework.
.SH SEE ALSO
pshellAggregator(1), PshellServer(3), PshellControl(3), TraceFilter(3), TraceLog(3)
.SH AUTHOR
Ron Iovine  --  github.com/RonIovine/pshell
